Repository CA-G12/react-class-husam-abdou, pull requests merged in 2022-09, with the labels that each got.

#5 2 create header
  src/App.css
  src/App.js
  src/component/Header.js
Labels: approve

#6 create carts and cart relates #3
  .vscode/settings.json
  src/App.js
  src/Components/Cart.js
  src/Components/Carts.js
Labels: awaite-reviwe

#9 Button
  src/App.js
  src/Components/Cart.js
  src/Components/Carts.js
  src/Components/Header.js
Labels: awaite-reviwe

#10 create navbar
  src/App.js
  src/Components/Header.js
  src/Components/Navbar.js
Labels: approve, awaite-reviwe

#12 create sarech
  src/App.js
  src/Components/Navbar.js
Labels: approve
